server:
  port: 8181
  
spring:
  profiles: dev
  application: 
    name: gdt
  cloud:
    config:
      uri: http://localhost:8888/gdt/dev
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: get_route
        uri: http://172.19.138.160:32030
        predicates:
        - Method=GET
        filters:
        - SetPath=/gamedata.lms.kr/v1.0/servers
      - id: post_route
        uri: http://192.168.212.7:30194
        predicates:
        - Method=POST
        filters:
        - SetPath=/gamedata.lms.kr/v1.0/servers

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh  
        
application:
  gdt:
    demo:
      name: game
      alias: data
      temp: hello world!!
