server:
  port: 8181
  
spring:
  profiles: dev
  application: 
    name: gdt
  cloud:
    config:
      uri: http://localhost:8888/gdt/dev
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: path_route
        uri: https://example.org
        predicates:
        - Method=GET

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh  
        
application:
  gdt:
    demo:
      name: game
      alias: data
      temp: hello world!!
